app/config/routes.rb
Rails.application.routes.draw do
  resources :poc, :search, :browse, :trigrams

  namespace :student do
    resource :add_course
  end










end

app/app/models/article.rb
class Article < ActiveRecord::Base
has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :student
  has_many :prepreqs, class_name: 'Course'
  has_many :coreqs, class_name: 'Course'
  has_many :semesters
  fuzzily_searchable :description

  def to_s
    "course_id: #{course_id} title: #{title} num_credits: #{num_credits}"
  end
end

app/app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :requirement
end

app/app/models/requirement.rb
class Requirement < ActiveRecord::Base
end

app/app/models/requirement_list.rb
# Requirement list is essentially a major, but it can also my a minor or an application domain or a liberal arts
# immersion, so the class is super generic
class RequirementList < ActiveRecord::Base
  has_many :requirements
end

app/app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :courses
end

app/app/models/school.rb
class School < ActiveRecord::Base
  hasMany :plans
end

app/app/models/semester.rb
class Semester < ActiveRecord::Base
end

app/app/models/student.rb
class Student < ActiveRecord::Base
  has_many :courses
  has_many :plans
end

app/app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
    # V1: grab all courses with the given ID
    # V2: grab all courses with the given ID -or- grab all courses with a
    #   fuzzy-search match with the search term, sorted by relevance
    @courses = get_courses_for_search_term(params[:search])
  end

  private
  def get_courses_for_search_term(search_term)
    # Check if the input is a course id
    if search_term =~ /[A-Z0-9]{4}-[0-9]{3}/
      [Course.where(course_id: search_term).take]
    else
      puts "Seaching for #{search_term}"
      Course.find_by_fuzzy_description(search_term, :limit => 10)
    end
  end
end

app/app/helpers/articles_helper.rb
module ArticlesHelper
end

app/app/helpers/browse_helper.rb
module BrowseHelper
end

app/app/helpers/comments_helper.rb
module CommentsHelper
end

app/app/helpers/course_helper.rb
module CourseHelper
end

app/app/helpers/poc_helper.rb
module PocHelper
end

app/app/helpers/search_helper.rb
module SearchHelper
end

app/app/helpers/student_helper.rb
module StudentHelper
end

app/app/helpers/trigrams_helper.rb
module TrigramsHelper
end

app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/app/views/search/_form.html.erb
<%= form_tag('/search', method: 'post') do %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search by class ID" %>
        <!-- In order to have the "search" icon in the button, we need to use plain HTML instead 
           of using a Rails form helper -->
    <button class="btn" type="submit"><i class="icon-search">Search</i></button>
  </div>
<% end %>

<script>
$('#search').on('keyup', function() {
    if(this.value.length > 1) {
        // Send off a search and display the results
        console.log(this.value);
    }
});
</script>
<%= yield %>

app/app/views/search/_search.html.erb
<div>
    <%= render 'search/form' %>
</div>
<div>
    <h3>Browse</h3>
    <p><%= link_to 'Classes', browse_path(:courses) %></p>
    <p><%= link_to 'Majors', browse_path(:majors) %></p>
    <p><%= link_to 'Minors', browse_path(:minors) %></p>
    <p><%= link_to 'Immersions', browse_path(:immersions) %></p>
</div>

app/app/views/search/create.html.erb
<!--
Shows the results of a search

Receives its data as an array of Course objects, sorted by relevance. For the
initial POC, this means that only the course with the matching course number
will be returned. However, once search-by-name is implemented (by zombies),
the list snould be all the classes that match sorted by matching score

The array should be in the @courses variable
-->

<div class="container">
    <div class="col-md-3">
        <!-- Placeholder div so our content is nice and centered -->
    </div>

    <div class="col-md-6">
        <!-- Display all the courses returned form the search -->

        <h2>Found courses:</h2>

        <% @courses.each do |course| %>
            <h2><%= course.title %></h2>
            <p><%= course.description %></p>
        <% end %>
    </div>

    <div class="col-md-3">
        <!-- Placeholder so nothing weird happens -->
    </div>
</div>